# Generated by Django 4.2.15 on 2024-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
