# Generated by Django 4.2.15 on 2024-09-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='academic/images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='activites/images'),
        ),
    ]
