# Generated by Django 4.2.15 on 2024-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='academic/images'),
        ),
    ]
