# Generated by Django 4.2.15 on 2024-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_subject_description_subject_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
