# Generated by Django 4.2.15 on 2024-09-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rating',
        ),
    ]
