# Generated by Django 4.2.15 on 2024-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_review_author_delete_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
