# Generated by Django 5.1.1 on 2024-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_student_photo_alter_subject_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
