# Generated by Django 4.2.15 on 2024-09-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_notice'),
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject')},
        ),
    ]
